name: Sunucuya Otomatik Dağıtım (Auto Deploy)

on:
  push:
    branches:
      - master # Eğer ana dalının adı master ise burayı master yap

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Oracle Sunucusuna Baglan ve Kodu Guncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/proje-kmyo-teknik-servis
            git pull origin master
